---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-jboss
  labels:
    app: maven-jboss
spec:
  replicas: 4
  selector:
    matchLabels:
      app: maven-jboss
  template:
    metadata:
      labels:
        app: maven-jboss
    spec:
      containers:
      - name: maven-jboss
        image: adityadevops/maven-jboss
        ports:
        - containerPort: 8080

