---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-jboss
  labels:
    app: maven-jboss
spec:
  replicas: 4
  selector:
    matchLabels:
      app: maven-jboss
  template:
    metadata:
      labels:
        app: maven-jboss
    spec:
      containers:
      - name: maven-jboss
        image: adityadevops/maven-jboss:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-jboss
spec:
  type: NodePort
  selector:
    app: maven-jboss
  ports:
  - port: 8080
    targetPort: 8080
